### ISSUE TITLE
Thumbnail URL for discord adapter does not resolve

### ISSUE THREAD

**Issue by Eeems** [flavorjones/webhook-notification-resource#9]
It looks like the subdomain no longer exists.

https://github.com/flavorjones/webhook-notification-resource/blob/master/resource/lib/adapters/discord_adapter.rb#L28

**Comment by flavorjones** [comment]
Ah, sorry about that. Please see https://github.com/flavorjones/webhook-notification-resource/issues/8 for more information about end-of-support for this resource, and let me know if you're interested in picking it up.

**Comment by Eeems** [comment]
Since the repo is not archived yet and there are still a couple of days before your deadline, it might make sense to leave this open just in case someone picks it up, or for if someone is looking at the archived version they'll be able to still see what issues are outstanding.

If this was written in something other than ruby, I might be interested in at least keeping things from breaking.

**Comment by flavorjones** [comment]
You don't need to become a maintainer to help fix this. I'd welcome a pull request to address this by replacing the hardcoded domain with the Concourse env var `$ATC_EXTERNAL_URL` and/or a configuration parameter; and I'd even be willing to pair on it with you.
